language: node_js
sudo: false
node_js:
  - "5.0"
env:
  - CORE=snes9x-next
  - CORE=vba-next
  - CORE=gambatte
  - CORE=nestopia
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.9
before_script:
  - git clone https://github.com/urho3d/emscripten-sdk.git && emscripten-sdk/emsdk activate --build=Release sdk-incoming-64bit && source emscripten-sdk/emsdk_env.sh && export EMSCRIPTEN_ROOT_PATH=$EMSCRIPTEN && export EMSCRIPTEN=1
script:
  - npm run build -- core/$CORE
  - npm test -- -g $CORE
