language: node_js
sudo: false
node_js:
  - "5.0"
env:
  global:
    - SDK=latest
  matrix:
    - CORE=snes9x-next
    - CORE=vba-next
    - CORE=gambatte
    - CORE=nestopia
    - CORE=picodrive
    - CORE=stella
    - CORE=gw
    - CORE=vecx
git:
  submodules: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
before_script:
  - |
    wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    mkdir cmake-dist
    tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz -C cmake-dist --strip-components=1
    export PATH=$PWD/cmake-dist/bin:$PATH
  - |
    git clone https://github.com/juj/emsdk.git
    cd emsdk
    ./emsdk update
    ./emsdk install $SDK
    ./emsdk activate $SDK
    source ./emsdk_env.sh
before_install:
  - git submodule update --init core/$CORE
script:
  - npm run build -- core/$CORE
  - npm test -- -g $CORE
cache:
  bundler: true
  directories:
    - node_modules
    - jspm_packages
    - emsdk
    - cmake-dist
