language: node_js
sudo: false
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
before_script:
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.sh
  - sh cmake-3.2.2-Linux-x86_64.sh --prefix=$HOME --exclude-subdir
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar xfz emsdk-portable.tar.gz
  - (cd emsdk_portable && ./emsdk update && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh)
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
script:
  - npm run build
